trigger: none

schedules:
  - cron: "*/5 * * * *"
    displayName: every 5 minutes
    branches:
      include:
        - main
    always: true

pool:
  vmImage: "ubuntu-18.04"

steps:
  - task: ShellScript@2
    inputs:
      scriptPath: script.sh
